### ISSUE TITLE
Installing msphpsql on a Redhat 7 with Plesk 12.5

### ISSUE THREAD

**Issue by Tklaversma** [Microsoft/msphpsql#185]
When I follow the tutorial below:
```
sudo su
yum-config-manager --add-repo https://apt-mo.trafficmanager.net/yumrepos/mssql-rhel7-release/
yum-config-manager --enable mssql-rhel7-release
wget "http://aka.ms/msodbcrhelpublickey/dpgswdist.v1.asc"
rpm --import dpgswdist.v1.asc
yum remove unixODBC #to avoid conflicts during installation
yum update
yum install msodbcsql unixODBC-utf16-devel
yum groupinstall "Development Tools"
```
I have a problem with `yum remove unixODBC`. Plesk uses this library for almost all Plesk-modules...so this cannot be removed.

I tried to skip this step, but then I get the error `Error: unixODBC-utf16 conflicts with unixODBC-2.3.1-11.el7.x86_64`.

Do anyone of you got a workaround to get this installed on a Linux CentOS 7 distribution with Plesk 12.5 on it?

Regards,
TK

**Comment by meet-bhagdev** [comment]
Try this :) This would Install the ODBC Driver on CentOS and take care of the conflict

```
sudo su 
wget https://raw.githubusercontent.com/Azure/msphpsql/PHP-7.0-Linux/ODBC%20install%20scripts/installodbc_redhat.sh 
sh installodbc_redhat.sh
```

**Comment by Tklaversma** [comment]
Thanks for the quick reaction.
Just to be sure, this won't break (delete) any existing Plesk modules/functionality?

**Comment by Tklaversma** [comment]
Ok, I figured it out.

Below you'll find the full process of installing MSPHPSQL on CentOS 7 with Plesk...
Hope I can help some other people with this:

```
# yum-config-manager --add-repo https://apt-mo.trafficmanager.net/yumrepos/mssql-rhel6-release/
# yum-config-manager --enable mssql-rhel6-release
# wget "http://aka.ms/msodbcrhelpublickey/dpgswdist.v1.asc"
# rpm --import dpgswdist.v1.asc

# cd /tmp/
# wget https://raw.githubusercontent.com/Azure/msphpsql/PHP-7.0-Linux/ODBC%20install%20scripts/installodbc_redhat.sh
# sh installodbc_redhat.sh
# yum update

# sudo pecl install sqlsrv-4.0.5
# sudo pecl install pdo_sqlsrv-4.0.5
# service httpd restart

# vim /opt/plesk/php/7.0/etc/php.d/sqlsrv.ini
Add the following:
	extension=/usr/lib64/php/modules/sqlsrv.so
	extension=/usr/lib64/php/modules/pdo_sqlsrv.so
# plesk bin php_handler --reread
```

**Comment by Tklaversma** [comment]
Just to be sure... if an update comes out, all we have to do is just `yum update` right?
If not, could you show me how to update this library..

**Comment by meet-bhagdev** [comment]
For ODBC driver, you can do the following:
`yum update msodbcsql`

For the PHP connector, you can do the following
```
pecl search sqlsrv #to get the latest version
pecl install sqlsrv-4.0.7 #this will update and overwrite the older version
pecl search pdo_sqlsrv #to get the latest version
pecl install pdo_sqlsrv-4.0.7 #this will update and overwrite the older version
```

**Comment by Tklaversma** [comment]
I got it all working now. You can close this issue.

**Comment by davidlapham** [comment]
@Tklaversma  Did you run into any errors when running the pecl commands? 

First issue was...
`checking whether we are using the GNU C++ compiler... no
checking whether g++ accepts -g... no
checking how to run the C++ preprocessor... /lib/cpp
configure: error: in `/tmp/pear-build-root8vzWJb/sqlsrv-4.0.7':
configure: error: C++ preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details
ERROR: `/tmp/sqlsrv/configure --with-php-config=/usr/bin/php-config' failed
`
which I solved with 
" yum install gcc-c++"

Now I'm getting...

`pecl install sqlsrv-4.1.6.1
Cannot load the ionCube PHP Loader - it was already loaded
downloading sqlsrv-4.1.6.1.tgz ...
Starting to download sqlsrv-4.1.6.1.tgz (192,120 bytes)
.........................................done: 192,120 bytes
33 source files, building
running: phpize
Configuring for:
PHP Api Version:         20100412
Zend Module Api No:      20100525
Zend Extension Api No:   220100525
building in /tmp/pear-build-root0OmjE3/sqlsrv-4.1.6.1
running: /tmp/sqlsrv/configure --with-php-config=/usr/bin/php-config
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib
checking for PHP extension directory... /usr/lib64/php/modules
checking for PHP installed headers prefix... /usr/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking whether to enable sqlsrv functions... yes, shared
checking for SQLSRV headers... /tmp/sqlsrv/shared/
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... (cached) gawk
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC -DPIC
checking if cc PIC flag -fPIC -DPIC works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking if cc supports -c -o file.o... (cached) yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
configure: creating ./config.status
config.status: creating config.h
config.status: executing libtool commands
running: make
/bin/sh /tmp/pear-build-root0OmjE3/sqlsrv-4.1.6.1/libtool --mode=compile g++ -std=c++11 -I. -I/tmp/sqlsrv -DPHP_ATOM_INC -I/tmp/pear-build-root0OmjE3/sqlsrv-4.1.6.1/include -I/tmp/pear-build-root0OmjE3/sqlsrv-4.1.6.1/main -I/tmp/sqlsrv -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/tmp/sqlsrv/shared/  -DHAVE_CONFIG_H  -std=c++11   -c /tmp/sqlsrv/conn.cpp -o conn.lo
libtool: compile:  g++ -std=c++11 -I. -I/tmp/sqlsrv -DPHP_ATOM_INC -I/tmp/pear-build-root0OmjE3/sqlsrv-4.1.6.1/include -I/tmp/pear-build-root0OmjE3/sqlsrv-4.1.6.1/main -I/tmp/sqlsrv -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/tmp/sqlsrv/shared/ -DHAVE_CONFIG_H -std=c++11 -c /tmp/sqlsrv/conn.cpp  -fPIC -DPIC -o .libs/conn.o
In file included from /tmp/sqlsrv/php_sqlsrv.h:25:0,
                 from /tmp/sqlsrv/conn.cpp:20:
/tmp/sqlsrv/shared/core_sqlsrv.h:2160:38: error: macro "ZVAL_STRINGL" requires 4 arguments, but only 3 given
    ZVAL_STRINGL(value_z, str, str_len);
                                      ^
/tmp/sqlsrv/shared/core_sqlsrv.h:2207:54: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
         int zr = ::add_assoc_string(array_z, key, val);
                                                      ^
/tmp/sqlsrv/shared/core_sqlsrv.h:2235:58: error: macro "zend_hash_get_current_data" requires 2 arguments, but only 1 given
   int zr = (output_data = ::zend_hash_get_current_data(ht)) != NULL ? SUCCESS : FAILURE;
                                                          ^
/tmp/sqlsrv/shared/core_sqlsrv.h:2259:70: error: macro "zend_hash_index_update" requires 5 arguments, but only 3 given
         int zr = (data_z = ::zend_hash_index_update(ht, index, data_z)) != NULL ? SUCCESS : FAILURE;
                                                                      ^
/tmp/sqlsrv/shared/core_sqlsrv.h:2284:64: error: macro "zend_hash_next_index_insert" requires 4 arguments, but only 2 given
         int zr = (data = ::zend_hash_next_index_insert(ht, data)) != NULL ? SUCCESS : FAILURE;
                                                                ^
In file included from /tmp/sqlsrv/conn.cpp:20:0:
/tmp/sqlsrv/php_sqlsrv.h:75:2: error: #error Trying to compile "Microsoft Drivers for PHP for SQL Server (SQLSRV Driver)" with an unsupported version of PHP
 #error Trying to compile "Microsoft Drivers for PHP for SQL Server (SQLSRV Driver)" with an unsupported version of PHP
  ^
In file included from /tmp/sqlsrv/php_sqlsrv.h:25:0,
                 from /tmp/sqlsrv/conn.cpp:20:
/tmp/sqlsrv/shared/core_sqlsrv.h:230:5: error: 'zend_long' does not name a type
     zend_long value;
     ^
/tmp/sqlsrv/shared/core_sqlsrv.h:244:5: error: 'zend_long' does not name a type
     zend_long value;
     ^
In file included from /usr/include/php/Zend/zend.h:831:0,
                 from /usr/include/php/main/php.h:34,
                 from /tmp/sqlsrv/shared/core_sqlsrv.h:34,
                 from /tmp/sqlsrv/php_sqlsrv.h:25,
                 from /tmp/sqlsrv/conn.cpp:20:
/tmp/sqlsrv/shared/core_sqlsrv.h: In member function 'void zval_auto_ptr::reset(zval*)':
/usr/include/php/Zend/zend_variables.h:57:76: error: cannot convert '_zval_struct*' to 'zval** {aka _zval_struct**}' for argument '1' to 'void _zval_ptr_dtor(zval**)'
 #define zval_ptr_dtor(zval_ptr) _zval_ptr_dtor((zval_ptr) ZEND_FILE_LINE_CC)
                                                                            ^
/tmp/sqlsrv/shared/core_sqlsrv.h:714:13: note: in expansion of macro 'zval_ptr_dtor'
             zval_ptr_dtor(_ptr );
             ^
In file included from /tmp/sqlsrv/php_sqlsrv.h:25:0,
                 from /tmp/sqlsrv/conn.cpp:20:
/tmp/sqlsrv/shared/core_sqlsrv.h: At global scope:
/tmp/sqlsrv/shared/core_sqlsrv.h:1292:5: error: 'zend_long' does not name a type
     zend_long buffered_query_limit;   // maximum allowed memory for a buffered query (measured in KB)
     ^
/tmp/sqlsrv/shared/core_sqlsrv.h:1447:18: error: 'zend_long' does not name a type
     static const zend_long BUFFERED_QUERY_LIMIT_DEFAULT = 10240;   // measured in KB
                  ^
/tmp/sqlsrv/shared/core_sqlsrv.h:1448:18: error: 'zend_long' does not name a type
     static const zend_long BUFFERED_QUERY_LIMIT_INVALID = 0;
                  ^
/tmp/sqlsrv/shared/core_sqlsrv.h: In function 'void core::sqlsrv_zval_stringl(zval*, const char*, std::size_t)':
/tmp/sqlsrv/shared/core_sqlsrv.h:2154:56: error: 'Z_STR_P' was not declared in this scope
   if (Z_TYPE_P(value_z) == IS_STRING && Z_STR_P(value_z) != NULL) {
                                                        ^
/tmp/sqlsrv/shared/core_sqlsrv.h:2155:4: error: 'zend_string' was not declared in this scope
    zend_string* temp_zstr = zend_string_init(str, str_len, 0);
    ^
/tmp/sqlsrv/shared/core_sqlsrv.h:2155:17: error: 'temp_zstr' was not declared in this scope
    zend_string* temp_zstr = zend_string_init(str, str_len, 0);
                 ^
/tmp/sqlsrv/shared/core_sqlsrv.h:2155:61: error: 'zend_string_init' was not declared in this scope
    zend_string* temp_zstr = zend_string_init(str, str_len, 0);
                                                             ^
/tmp/sqlsrv/shared/core_sqlsrv.h:2156:40: error: 'zend_string_release' was not declared in this scope
    zend_string_release(Z_STR_P(value_z));
                                        ^
/tmp/sqlsrv/shared/core_sqlsrv.h:2157:35: error: 'ZVAL_NEW_STR' was not declared in this scope
    ZVAL_NEW_STR(value_z, temp_zstr);
                                   ^
/tmp/sqlsrv/shared/core_sqlsrv.h:2160:4: error: 'ZVAL_STRINGL' was not declared in this scope
    ZVAL_STRINGL(value_z, str, str_len);
    ^
/tmp/sqlsrv/shared/core_sqlsrv.h: At global scope:
/tmp/sqlsrv/shared/core_sqlsrv.h:2197:93: error: 'zend_long' has not been declared
     inline void sqlsrv_add_assoc_long( sqlsrv_context& ctx, zval* array_z, const char* key, zend_long val TSRMLS_DC )
                                                                                             ^
/tmp/sqlsrv/shared/core_sqlsrv.h: In function 'void core::sqlsrv_add_assoc_string(sqlsrv_context&, zval*, const char*, char*, bool)':
/tmp/sqlsrv/shared/core_sqlsrv.h:2207:18: error: '::add_assoc_string' has not been declared
         int zr = ::add_assoc_string(array_z, key, val);
                  ^
In file included from /usr/include/php/main/php.h:396:0,
                 from /tmp/sqlsrv/shared/core_sqlsrv.h:34,
                 from /tmp/sqlsrv/php_sqlsrv.h:25,
                 from /tmp/sqlsrv/conn.cpp:20:
/tmp/sqlsrv/shared/core_sqlsrv.h: In function 'void core::sqlsrv_php_stream_from_zval_no_verify(sqlsrv_context&, php_stream*&, zval*)':
/usr/include/php/main/php_streams.h:263:182: error: cannot convert 'zval* {aka _zval_struct*}' to 'zval** {aka _zval_struct**}' for argument '1' to 'void* zend_fetch_resource(zval**, int, const char*, int*, int, ...)'
 #define php_stream_from_zval_no_verify(xstr, ppzval) (xstr) = (php_stream*)zend_fetch_resource((ppzval) TSRMLS_CC, -1, "stream", NULL, 2, php_file_le_stream(), php_file_le_pstream())
                                                                                                                                                                                      ^
/tmp/sqlsrv/shared/core_sqlsrv.h:2227:9: note: in expansion of macro 'php_stream_from_zval_no_verify'
         php_stream_from_zval_no_verify( stream, stream_z );
         ^
In file included from /tmp/sqlsrv/php_sqlsrv.h:25:0,
                 from /tmp/sqlsrv/conn.cpp:20:
/tmp/sqlsrv/shared/core_sqlsrv.h: In function 'void core::sqlsrv_zend_hash_get_current_data(sqlsrv_context&, HashTable*, zval*&)':
/tmp/sqlsrv/shared/core_sqlsrv.h:2235:27: error: '::zend_hash_get_current_data' has not been declared
   int zr = (output_data = ::zend_hash_get_current_data(ht)) != NULL ? SUCCESS : FAILURE;
                           ^
/tmp/sqlsrv/shared/core_sqlsrv.h: In function 'void core::sqlsrv_zend_hash_get_current_data_ptr(sqlsrv_context&, HashTable*, void*&)':
/tmp/sqlsrv/shared/core_sqlsrv.h:2243:33: error: '::zend_hash_get_current_data_ptr' has not been declared
         int zr = (output_data = ::zend_hash_get_current_data_ptr(ht)) != NULL ? SUCCESS : FAILURE;
                                 ^
/tmp/sqlsrv/shared/core_sqlsrv.h: In function 'void core::sqlsrv_zend_hash_index_update(sqlsrv_context&, HashTable*, zend_ulong, zval*)':
/tmp/sqlsrv/shared/core_sqlsrv.h:2259:28: error: '::zend_hash_index_update' has not been declared
         int zr = (data_z = ::zend_hash_index_update(ht, index, data_z)) != NULL ? SUCCESS : FAILURE;
                            ^
/tmp/sqlsrv/shared/core_sqlsrv.h: In function 'void core::sqlsrv_zend_hash_index_update_ptr(sqlsrv_context&, HashTable*, zend_ulong, void*)':
/tmp/sqlsrv/shared/core_sqlsrv.h:2267:27: error: '::zend_hash_index_update_ptr' has not been declared
         int zr = (pData = ::zend_hash_index_update_ptr(ht, index, pData)) != NULL ? SUCCESS : FAILURE;
                           ^
/tmp/sqlsrv/shared/core_sqlsrv.h: In function 'void core::sqlsrv_zend_hash_index_update_mem(sqlsrv_context&, HashTable*, zend_ulong, void*, std::size_t)':
/tmp/sqlsrv/shared/core_sqlsrv.h:2276:21: error: '::zend_hash_index_update_mem' has not been declared
   int zr = (pData = ::zend_hash_index_update_mem(ht, index, pData, size)) != NULL ? SUCCESS : FAILURE;
                     ^
/tmp/sqlsrv/shared/core_sqlsrv.h: In function 'void core::sqlsrv_zend_hash_next_index_insert(sqlsrv_context&, HashTable*, zval*)':
/tmp/sqlsrv/shared/core_sqlsrv.h:2284:26: error: '::zend_hash_next_index_insert' has not been declared
         int zr = (data = ::zend_hash_next_index_insert(ht, data)) != NULL ? SUCCESS : FAILURE;
                          ^
/tmp/sqlsrv/shared/core_sqlsrv.h: In function 'void core::sqlsrv_zend_hash_next_index_insert_mem(sqlsrv_context&, HashTable*, void*, uint)':
/tmp/sqlsrv/shared/core_sqlsrv.h:2292:20: error: '::zend_hash_next_index_insert_mem' has not been declared
   int zr = (data = ::zend_hash_next_index_insert_mem(ht, data, data_size)) != NULL ? SUCCESS : FAILURE;
                    ^
/tmp/sqlsrv/shared/core_sqlsrv.h: In function 'void core::sqlsrv_zend_hash_next_index_insert_ptr(sqlsrv_context&, HashTable*, void*)':
/tmp/sqlsrv/shared/core_sqlsrv.h:2300:26: error: '::zend_hash_next_index_insert_ptr' has not been declared
         int zr = (data = ::zend_hash_next_index_insert_ptr(ht, data)) != NULL ? SUCCESS : FAILURE;
                          ^
In file included from /tmp/sqlsrv/conn.cpp:20:0:
/tmp/sqlsrv/php_sqlsrv.h: At global scope:
/tmp/sqlsrv/php_sqlsrv.h:151:32: error: variable or field 'sqlsrv_conn_dtor' declared void
 void __cdecl sqlsrv_conn_dtor( zend_resource *rsrc TSRMLS_DC );
                                ^
/tmp/sqlsrv/php_sqlsrv.h:151:32: error: 'zend_resource' was not declared in this scope
/tmp/sqlsrv/php_sqlsrv.h:151:47: error: 'rsrc' was not declared in this scope
 void __cdecl sqlsrv_conn_dtor( zend_resource *rsrc TSRMLS_DC );
                                               ^
/tmp/sqlsrv/php_sqlsrv.h:226:32: error: variable or field 'sqlsrv_stmt_dtor' declared void
 void __cdecl sqlsrv_stmt_dtor( zend_resource *rsrc TSRMLS_DC );
                                ^
/tmp/sqlsrv/php_sqlsrv.h:226:32: error: 'zend_resource' was not declared in this scope
/tmp/sqlsrv/php_sqlsrv.h:226:47: error: 'rsrc' was not declared in this scope
 void __cdecl sqlsrv_stmt_dtor( zend_resource *rsrc TSRMLS_DC );
                                               ^
/tmp/sqlsrv/php_sqlsrv.h:272:1: error: 'zend_long' does not name a type
 zend_long log_severity;
 ^
/tmp/sqlsrv/php_sqlsrv.h:273:1: error: 'zend_long' does not name a type
 zend_long log_subsystems;
 ^
/tmp/sqlsrv/php_sqlsrv.h:274:1: error: 'zend_long' does not name a type
 zend_long current_subsystem;
 ^
/tmp/sqlsrv/php_sqlsrv.h:276:1: error: 'zend_long' does not name a type
 zend_long buffered_query_limit;
 ^
In file included from /usr/include/php/main/php_ini.h:24:0,
                 from /usr/include/php/main/fopen_wrappers.h:26,
                 from /usr/include/php/main/php.h:398,
                 from /tmp/sqlsrv/shared/core_sqlsrv.h:34,
                 from /tmp/sqlsrv/php_sqlsrv.h:25,
                 from /tmp/sqlsrv/conn.cpp:20:
/tmp/sqlsrv/php_sqlsrv.h:302:85: error: 'zend_sqlsrv_globals' has no member named 'log_severity'
     STD_PHP_INI_ENTRY( INI_PREFIX INI_LOG_SEVERITY, "0", PHP_INI_ALL, OnUpdateLong, log_severity, zend_sqlsrv_globals,
                                                                                     ^
/usr/include/php/Zend/zend_ini.h:118:50: note: in definition of macro 'ZEND_INI_ENTRY3_EX'
  { 0, modifiable, name, sizeof(name), on_modify, arg1, arg2, arg3, default_value, sizeof(default_value)-1, NULL, 0, 0, 0, displayer },
                                                  ^
/usr/include/php/Zend/zend_ini.h:127:2: note: in expansion of macro 'ZEND_INI_ENTRY2_EX'
  ZEND_INI_ENTRY2_EX(name, default_value, modifiable, on_modify, arg1, arg2, NULL)
  ^
/usr/include/php/Zend/zend_ini.h:150:2: note: in expansion of macro 'ZEND_INI_ENTRY2'
  ZEND_INI_ENTRY2(name, default_value, modifiable, on_modify, (void *) XtOffsetOf(struct_type, property_name), (void *) &struct_ptr)
  ^
/usr/include/php/Zend/zend_ini.h:55:36: note: in expansion of macro 'XtOffset'
 # define XtOffsetOf(s_type, field) XtOffset(s_type*, field)
                                    ^
/usr/include/php/Zend/zend_ini.h:150:71: note: in expansion of macro 'XtOffsetOf'
  ZEND_INI_ENTRY2(name, default_value, modifiable, on_modify, (void *) XtOffsetOf(struct_type, property_name), (void *) &struct_ptr)
                                                                       ^
/usr/include/php/main/php_ini.h:67:28: note: in expansion of macro 'STD_ZEND_INI_ENTRY'
 #define STD_PHP_INI_ENTRY  STD_ZEND_INI_ENTRY
                            ^
/tmp/sqlsrv/php_sqlsrv.h:302:5: note: in expansion of macro 'STD_PHP_INI_ENTRY'
     STD_PHP_INI_ENTRY( INI_PREFIX INI_LOG_SEVERITY, "0", PHP_INI_ALL, OnUpdateLong, log_severity, zend_sqlsrv_globals,
     ^
/tmp/sqlsrv/php_sqlsrv.h:304:87: error: 'zend_sqlsrv_globals' has no member named 'log_subsystems'
     STD_PHP_INI_ENTRY( INI_PREFIX INI_LOG_SUBSYSTEMS, "0", PHP_INI_ALL, OnUpdateLong, log_subsystems, zend_sqlsrv_globals,
                                                                                       ^
/usr/include/php/Zend/zend_ini.h:118:50: note: in definition of macro 'ZEND_INI_ENTRY3_EX'
  { 0, modifiable, name, sizeof(name), on_modify, arg1, arg2, arg3, default_value, sizeof(default_value)-1, NULL, 0, 0, 0, displayer },
                                                  ^
/usr/include/php/Zend/zend_ini.h:127:2: note: in expansion of macro 'ZEND_INI_ENTRY2_EX'
  ZEND_INI_ENTRY2_EX(name, default_value, modifiable, on_modify, arg1, arg2, NULL)
  ^
/usr/include/php/Zend/zend_ini.h:150:2: note: in expansion of macro 'ZEND_INI_ENTRY2'
  ZEND_INI_ENTRY2(name, default_value, modifiable, on_modify, (void *) XtOffsetOf(struct_type, property_name), (void *) &struct_ptr)
  ^
/usr/include/php/Zend/zend_ini.h:55:36: note: in expansion of macro 'XtOffset'
 # define XtOffsetOf(s_type, field) XtOffset(s_type*, field)
                                    ^
/usr/include/php/Zend/zend_ini.h:150:71: note: in expansion of macro 'XtOffsetOf'
  ZEND_INI_ENTRY2(name, default_value, modifiable, on_modify, (void *) XtOffsetOf(struct_type, property_name), (void *) &struct_ptr)
                                                                       ^
/usr/include/php/main/php_ini.h:67:28: note: in expansion of macro 'STD_ZEND_INI_ENTRY'
 #define STD_PHP_INI_ENTRY  STD_ZEND_INI_ENTRY
                            ^
/tmp/sqlsrv/php_sqlsrv.h:304:5: note: in expansion of macro 'STD_PHP_INI_ENTRY'
     STD_PHP_INI_ENTRY( INI_PREFIX INI_LOG_SUBSYSTEMS, "0", PHP_INI_ALL, OnUpdateLong, log_subsystems, zend_sqlsrv_globals,
     ^
/tmp/sqlsrv/php_sqlsrv.h:306:122: error: 'zend_sqlsrv_globals' has no member named 'buffered_query_limit'
     STD_PHP_INI_ENTRY( INI_PREFIX INI_BUFFERED_QUERY_LIMIT, INI_BUFFERED_QUERY_LIMIT_DEFAULT, PHP_INI_ALL, OnUpdateLong, buffered_query_limit,
                                                                                                                          ^
/usr/include/php/Zend/zend_ini.h:118:50: note: in definition of macro 'ZEND_INI_ENTRY3_EX'
  { 0, modifiable, name, sizeof(name), on_modify, arg1, arg2, arg3, default_value, sizeof(default_value)-1, NULL, 0, 0, 0, displayer },
                                                  ^
/usr/include/php/Zend/zend_ini.h:127:2: note: in expansion of macro 'ZEND_INI_ENTRY2_EX'
  ZEND_INI_ENTRY2_EX(name, default_value, modifiable, on_modify, arg1, arg2, NULL)
  ^
/usr/include/php/Zend/zend_ini.h:150:2: note: in expansion of macro 'ZEND_INI_ENTRY2'
  ZEND_INI_ENTRY2(name, default_value, modifiable, on_modify, (void *) XtOffsetOf(struct_type, property_name), (void *) &struct_ptr)
  ^
/usr/include/php/Zend/zend_ini.h:55:36: note: in expansion of macro 'XtOffset'
 # define XtOffsetOf(s_type, field) XtOffset(s_type*, field)
                                    ^
/usr/include/php/Zend/zend_ini.h:150:71: note: in expansion of macro 'XtOffsetOf'
  ZEND_INI_ENTRY2(name, default_value, modifiable, on_modify, (void *) XtOffsetOf(struct_type, property_name), (void *) &struct_ptr)
                                                                       ^
/usr/include/php/main/php_ini.h:67:28: note: in expansion of macro 'STD_ZEND_INI_ENTRY'
 #define STD_PHP_INI_ENTRY  STD_ZEND_INI_ENTRY
                            ^
/tmp/sqlsrv/php_sqlsrv.h:306:5: note: in expansion of macro 'STD_PHP_INI_ENTRY'
     STD_PHP_INI_ENTRY( INI_PREFIX INI_BUFFERED_QUERY_LIMIT, INI_BUFFERED_QUERY_LIMIT_DEFAULT, PHP_INI_ALL, OnUpdateLong, buffered_query_limit,
     ^
In file included from /tmp/sqlsrv/conn.cpp:20:0:
/tmp/sqlsrv/php_sqlsrv.h:384:33: error: variable or field 'sqlsrv_error_dtor' declared void
 void __cdecl sqlsrv_error_dtor( zend_resource *rsrc TSRMLS_DC );
                                 ^
/tmp/sqlsrv/php_sqlsrv.h:384:33: error: 'zend_resource' was not declared in this scope
/tmp/sqlsrv/php_sqlsrv.h:384:48: error: 'rsrc' was not declared in this scope
 void __cdecl sqlsrv_error_dtor( zend_resource *rsrc TSRMLS_DC );
                                                ^
In file included from /usr/include/php/Zend/zend.h:830:0,
                 from /usr/include/php/main/php.h:34,
                 from /tmp/sqlsrv/shared/core_sqlsrv.h:34,
                 from /tmp/sqlsrv/php_sqlsrv.h:25,
                 from /tmp/sqlsrv/conn.cpp:20:
/tmp/sqlsrv/php_sqlsrv.h: In function 'void reset_errors()':
/tmp/sqlsrv/php_sqlsrv.h:285:50: error: 'sqlsrv' was not declared in this scope
 #define SQLSRV_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(sqlsrv, v)
                                                  ^
/usr/include/php/Zend/zend_operators.h:460:24: note: in definition of macro 'Z_TYPE'
 #define Z_TYPE(zval)  (zval).type
                        ^
/tmp/sqlsrv/php_sqlsrv.h:389:17: note: in expansion of macro 'SQLSRV_G'
     if( Z_TYPE( SQLSRV_G( errors )) != IS_ARRAY && Z_TYPE( SQLSRV_G( errors )) != IS_NULL ) {
                 ^
/tmp/sqlsrv/php_sqlsrv.h:389:27: error: 'errors' was not declared in this scope
     if( Z_TYPE( SQLSRV_G( errors )) != IS_ARRAY && Z_TYPE( SQLSRV_G( errors )) != IS_NULL ) {
                           ^
/usr/include/php/Zend/zend_operators.h:460:24: note: in definition of macro 'Z_TYPE'
 #define Z_TYPE(zval)  (zval).type
                        ^
/tmp/sqlsrv/php_sqlsrv.h:389:17: note: in expansion of macro 'SQLSRV_G'
     if( Z_TYPE( SQLSRV_G( errors )) != IS_ARRAY && Z_TYPE( SQLSRV_G( errors )) != IS_NULL ) {
                 ^
/tmp/sqlsrv/php_sqlsrv.h:285:59: error: 'ZEND_MODULE_GLOBALS_ACCESSOR' was not declared in this scope
 #define SQLSRV_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(sqlsrv, v)
                                                           ^
/usr/include/php/Zend/zend_operators.h:460:24: note: in definition of macro 'Z_TYPE'
 #define Z_TYPE(zval)  (zval).type
                        ^
/tmp/sqlsrv/php_sqlsrv.h:389:17: note: in expansion of macro 'SQLSRV_G'
     if( Z_TYPE( SQLSRV_G( errors )) != IS_ARRAY && Z_TYPE( SQLSRV_G( errors )) != IS_NULL ) {
                 ^
/tmp/sqlsrv/php_sqlsrv.h:285:50: error: 'sqlsrv' was not declared in this scope
 #define SQLSRV_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(sqlsrv, v)
                                                  ^
/usr/include/php/Zend/zend_operators.h:460:24: note: in definition of macro 'Z_TYPE'
 #define Z_TYPE(zval)  (zval).type
                        ^
/tmp/sqlsrv/php_sqlsrv.h:392:17: note: in expansion of macro 'SQLSRV_G'
     if( Z_TYPE( SQLSRV_G( warnings )) != IS_ARRAY && Z_TYPE( SQLSRV_G( warnings )) != IS_NULL ) {
                 ^
/tmp/sqlsrv/php_sqlsrv.h:392:27: error: 'warnings' was not declared in this scope
     if( Z_TYPE( SQLSRV_G( warnings )) != IS_ARRAY && Z_TYPE( SQLSRV_G( warnings )) != IS_NULL ) {
                           ^
/usr/include/php/Zend/zend_operators.h:460:24: note: in definition of macro 'Z_TYPE'
 #define Z_TYPE(zval)  (zval).type
                        ^
/tmp/sqlsrv/php_sqlsrv.h:392:17: note: in expansion of macro 'SQLSRV_G'
     if( Z_TYPE( SQLSRV_G( warnings )) != IS_ARRAY && Z_TYPE( SQLSRV_G( warnings )) != IS_NULL ) {
                 ^
/tmp/sqlsrv/php_sqlsrv.h:285:59: error: 'ZEND_MODULE_GLOBALS_ACCESSOR' was not declared in this scope
 #define SQLSRV_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(sqlsrv, v)
                                                           ^
/usr/include/php/Zend/zend_operators.h:460:24: note: in definition of macro 'Z_TYPE'
 #define Z_TYPE(zval)  (zval).type
                        ^
/tmp/sqlsrv/php_sqlsrv.h:392:17: note: in expansion of macro 'SQLSRV_G'
     if( Z_TYPE( SQLSRV_G( warnings )) != IS_ARRAY && Z_TYPE( SQLSRV_G( warnings )) != IS_NULL ) {
                 ^
/tmp/sqlsrv/php_sqlsrv.h:285:50: error: 'sqlsrv' was not declared in this scope
 #define SQLSRV_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(sqlsrv, v)
                                                  ^
/usr/include/php/Zend/zend_operators.h:460:24: note: in definition of macro 'Z_TYPE'
 #define Z_TYPE(zval)  (zval).type
                        ^
/tmp/sqlsrv/php_sqlsrv.h:396:17: note: in expansion of macro 'SQLSRV_G'
     if( Z_TYPE( SQLSRV_G( errors )) == IS_ARRAY ) {
                 ^
/tmp/sqlsrv/php_sqlsrv.h:396:27: error: 'errors' was not declared in this scope
     if( Z_TYPE( SQLSRV_G( errors )) == IS_ARRAY ) {
                           ^
/usr/include/php/Zend/zend_operators.h:460:24: note: in definition of macro 'Z_TYPE'
 #define Z_TYPE(zval)  (zval).type
                        ^
/tmp/sqlsrv/php_sqlsrv.h:396:17: note: in expansion of macro 'SQLSRV_G'
     if( Z_TYPE( SQLSRV_G( errors )) == IS_ARRAY ) {
                 ^
/tmp/sqlsrv/php_sqlsrv.h:285:59: error: 'ZEND_MODULE_GLOBALS_ACCESSOR' was not declared in this scope
 #define SQLSRV_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(sqlsrv, v)
                                                           ^
/usr/include/php/Zend/zend_operators.h:460:24: note: in definition of macro 'Z_TYPE'
 #define Z_TYPE(zval)  (zval).type
                        ^
/tmp/sqlsrv/php_sqlsrv.h:396:17: note: in expansion of macro 'SQLSRV_G'
     if( Z_TYPE( SQLSRV_G( errors )) == IS_ARRAY ) {
                 ^
/tmp/sqlsrv/php_sqlsrv.h:285:50: error: 'sqlsrv' was not declared in this scope
 #define SQLSRV_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(sqlsrv, v)
                                                  ^
/usr/include/php/Zend/zend_operators.h:460:24: note: in definition of macro 'Z_TYPE'
 #define Z_TYPE(zval)  (zval).type
                        ^
/tmp/sqlsrv/php_sqlsrv.h:400:17: note: in expansion of macro 'SQLSRV_G'
     if( Z_TYPE( SQLSRV_G( warnings )) == IS_ARRAY ) {
                 ^
/tmp/sqlsrv/php_sqlsrv.h:400:27: error: 'warnings' was not declared in this scope
     if( Z_TYPE( SQLSRV_G( warnings )) == IS_ARRAY ) {
                           ^
/usr/include/php/Zend/zend_operators.h:460:24: note: in definition of macro 'Z_TYPE'
 #define Z_TYPE(zval)  (zval).type
                        ^
/tmp/sqlsrv/php_sqlsrv.h:400:17: note: in expansion of macro 'SQLSRV_G'
     if( Z_TYPE( SQLSRV_G( warnings )) == IS_ARRAY ) {
                 ^
/tmp/sqlsrv/php_sqlsrv.h:285:59: error: 'ZEND_MODULE_GLOBALS_ACCESSOR' was not declared in this scope
 #define SQLSRV_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(sqlsrv, v)
                                                           ^
/usr/include/php/Zend/zend_operators.h:460:24: note: in definition of macro 'Z_TYPE'
 #define Z_TYPE(zval)  (zval).type
                        ^
/tmp/sqlsrv/php_sqlsrv.h:400:17: note: in expansion of macro 'SQLSRV_G'
     if( Z_TYPE( SQLSRV_G( warnings )) == IS_ARRAY ) {
                 ^
/tmp/sqlsrv/php_sqlsrv.h:285:50: error: 'sqlsrv' was not declared in this scope
 #define SQLSRV_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(sqlsrv, v)
                                                  ^
/usr/include/php/Zend/zend_operators.h:460:24: note: in definition of macro 'Z_TYPE'
 #define Z_TYPE(zval)  (zval).type
                        ^
/usr/include/php/Zend/zend_API.h:555:3: note: in expansion of macro 'Z_TYPE_P'
   Z_TYPE_P(z) = IS_NULL;  \
   ^
/tmp/sqlsrv/php_sqlsrv.h:405:5: note: in expansion of macro 'ZVAL_NULL'
     ZVAL_NULL( &SQLSRV_G( errors ));
     ^
/tmp/sqlsrv/php_sqlsrv.h:405:17: note: in expansion of macro 'SQLSRV_G'
     ZVAL_NULL( &SQLSRV_G( errors ));
                 ^
/tmp/sqlsrv/php_sqlsrv.h:405:27: error: 'errors' was not declared in this scope
     ZVAL_NULL( &SQLSRV_G( errors ));
                           ^
/usr/include/php/Zend/zend_operators.h:460:24: note: in definition of macro 'Z_TYPE'
 #define Z_TYPE(zval)  (zval).type
                        ^
/usr/include/php/Zend/zend_API.h:555:3: note: in expansion of macro 'Z_TYPE_P'
   Z_TYPE_P(z) = IS_NULL;  \
   ^
/tmp/sqlsrv/php_sqlsrv.h:405:5: note: in expansion of macro 'ZVAL_NULL'
     ZVAL_NULL( &SQLSRV_G( errors ));
     ^
/tmp/sqlsrv/php_sqlsrv.h:405:17: note: in expansion of macro 'SQLSRV_G'
     ZVAL_NULL( &SQLSRV_G( errors ));
                 ^
/tmp/sqlsrv/php_sqlsrv.h:285:59: error: 'ZEND_MODULE_GLOBALS_ACCESSOR' was not declared in this scope
 #define SQLSRV_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(sqlsrv, v)
                                                           ^
/usr/include/php/Zend/zend_operators.h:460:24: note: in definition of macro 'Z_TYPE'
 #define Z_TYPE(zval)  (zval).type
                        ^
/usr/include/php/Zend/zend_API.h:555:3: note: in expansion of macro 'Z_TYPE_P'
   Z_TYPE_P(z) = IS_NULL;  \
   ^
/tmp/sqlsrv/php_sqlsrv.h:405:5: note: in expansion of macro 'ZVAL_NULL'
     ZVAL_NULL( &SQLSRV_G( errors ));
     ^
/tmp/sqlsrv/php_sqlsrv.h:405:17: note: in expansion of macro 'SQLSRV_G'
     ZVAL_NULL( &SQLSRV_G( errors ));
                 ^
/tmp/sqlsrv/php_sqlsrv.h:285:50: error: 'sqlsrv' was not declared in this scope
 #define SQLSRV_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(sqlsrv, v)
                                                  ^
/usr/include/php/Zend/zend_operators.h:460:24: note: in definition of macro 'Z_TYPE'
 #define Z_TYPE(zval)  (zval).type
                        ^
/usr/include/php/Zend/zend_API.h:555:3: note: in expansion of macro 'Z_TYPE_P'
   Z_TYPE_P(z) = IS_NULL;  \
   ^
/tmp/sqlsrv/php_sqlsrv.h:406:5: note: in expansion of macro 'ZVAL_NULL'
     ZVAL_NULL( &SQLSRV_G( warnings ));
     ^
/tmp/sqlsrv/php_sqlsrv.h:406:17: note: in expansion of macro 'SQLSRV_G'
     ZVAL_NULL( &SQLSRV_G( warnings ));
                 ^
/tmp/sqlsrv/php_sqlsrv.h:406:27: error: 'warnings' was not declared in this scope
     ZVAL_NULL( &SQLSRV_G( warnings ));
                           ^
/usr/include/php/Zend/zend_operators.h:460:24: note: in definition of macro 'Z_TYPE'
 #define Z_TYPE(zval)  (zval).type
                        ^
/usr/include/php/Zend/zend_API.h:555:3: note: in expansion of macro 'Z_TYPE_P'
   Z_TYPE_P(z) = IS_NULL;  \
   ^
/tmp/sqlsrv/php_sqlsrv.h:406:5: note: in expansion of macro 'ZVAL_NULL'
     ZVAL_NULL( &SQLSRV_G( warnings ));
     ^
/tmp/sqlsrv/php_sqlsrv.h:406:17: note: in expansion of macro 'SQLSRV_G'
     ZVAL_NULL( &SQLSRV_G( warnings ));
                 ^
/tmp/sqlsrv/php_sqlsrv.h:285:59: error: 'ZEND_MODULE_GLOBALS_ACCESSOR' was not declared in this scope
 #define SQLSRV_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(sqlsrv, v)
                                                           ^
/usr/include/php/Zend/zend_operators.h:460:24: note: in definition of macro 'Z_TYPE'
 #define Z_TYPE(zval)  (zval).type
                        ^
/usr/include/php/Zend/zend_API.h:555:3: note: in expansion of macro 'Z_TYPE_P'
   Z_TYPE_P(z) = IS_NULL;  \
   ^
/tmp/sqlsrv/php_sqlsrv.h:406:5: note: in expansion of macro 'ZVAL_NULL'
     ZVAL_NULL( &SQLSRV_G( warnings ));
     ^
/tmp/sqlsrv/php_sqlsrv.h:406:17: note: in expansion of macro 'SQLSRV_G'
     ZVAL_NULL( &SQLSRV_G( warnings ));
                 ^
In file included from /tmp/sqlsrv/conn.cpp:20:0:
/tmp/sqlsrv/php_sqlsrv.h: In function 'void ss::zend_register_resource(zval&, void*, int, char*)':
/tmp/sqlsrv/php_sqlsrv.h:495:45: error: 'Z_RES' was not declared in this scope
         int zr = (NULL != (Z_RES(rsrc_result) = ::zend_register_resource(rsrc_pointer, rsrc_type)) ? SUCCESS : FAILURE);
                                             ^
/tmp/sqlsrv/php_sqlsrv.h:495:97: error: invalid conversion from 'void*' to 'zval* {aka _zval_struct*}' [-fpermissive]
         int zr = (NULL != (Z_RES(rsrc_result) = ::zend_register_resource(rsrc_pointer, rsrc_type)) ? SUCCESS : FAILURE);
                                                                                                 ^
/tmp/sqlsrv/php_sqlsrv.h:495:97: error: invalid conversion from 'int' to 'void*' [-fpermissive]
/tmp/sqlsrv/php_sqlsrv.h:495:97: error: too few arguments to function 'int zend_register_resource(zval*, void*, int)'
In file included from /usr/include/php/Zend/zend_API.h:27:0,
                 from /usr/include/php/main/php.h:38,
                 from /tmp/sqlsrv/shared/core_sqlsrv.h:34,
                 from /tmp/sqlsrv/php_sqlsrv.h:25,
                 from /tmp/sqlsrv/conn.cpp:20:
/usr/include/php/Zend/zend_list.h:82:14: note: declared here
 ZEND_API int zend_register_resource(zval *rsrc_result, void *rsrc_pointer, int rsrc_type TSRMLS_DC);
              ^
In file included from /tmp/sqlsrv/conn.cpp:20:0:
/tmp/sqlsrv/php_sqlsrv.h:500:32: error: 'Z_TYPE_INFO' was not declared in this scope
         Z_TYPE_INFO(rsrc_result) = IS_RESOURCE_EX;
                                ^
/tmp/sqlsrv/php_sqlsrv.h:500:36: error: 'IS_RESOURCE_EX' was not declared in this scope
         Z_TYPE_INFO(rsrc_result) = IS_RESOURCE_EX;
                                    ^
/tmp/sqlsrv/php_sqlsrv.h: In function 'H* process_params(int, zval*, zval**, zval*, int, const char*, const char*, size_t, ...)':
/tmp/sqlsrv/php_sqlsrv.h:598:62: error: there are no arguments to 'Z_RES_P' that depend on a template parameter, so a declaration of 'Z_RES_P' must be available [-fpermissive]
         h = static_cast<H*>( zend_fetch_resource(Z_RES_P(rsrc) TSRMLS_CC, H::resource_name, H::descriptor ));
                                                              ^
/tmp/sqlsrv/php_sqlsrv.h:598:62: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/tmp/sqlsrv/conn.cpp: In static member function 'static void {anonymous}::conn_char_set_func::func(const connection_option*, zval*, sqlsrv_conn*, std::string&)':
/tmp/sqlsrv/conn.cpp:58:4: error: 'zend_string' was not declared in this scope
    zend_string* key = NULL;
    ^
/tmp/sqlsrv/conn.cpp:58:17: error: 'key' was not declared in this scope
    zend_string* key = NULL;
                 ^
/tmp/sqlsrv/conn.cpp:61:79: error: 'ZEND_HASH_FOREACH_KEY_PTR' was not declared in this scope
    ZEND_HASH_FOREACH_KEY_PTR( g_ss_encodings_ht, index, key, ss_encoding_temp ) {
                                                                               ^
/tmp/sqlsrv/conn.cpp:61:81: error: expected ';' before '{' token
    ZEND_HASH_FOREACH_KEY_PTR( g_ss_encodings_ht, index, key, ss_encoding_temp ) {
                                                                                 ^
/tmp/sqlsrv/conn.cpp:76:5: error: expected '}' at end of input
     }
     ^
/tmp/sqlsrv/conn.cpp: In static member function 'static void {anonymous}::bool_conn_attr_func<Attr>::func(const connection_option*, zval*, sqlsrv_conn*, std::string&)':
/tmp/sqlsrv/conn.cpp:119:71: error: 'zend_long' was not declared in this scope
     core::SQLSetConnectAttr(conn, Attr, reinterpret_cast<SQLPOINTER>((zend_long)zend_is_true(value)),
                                                                       ^
/tmp/sqlsrv/conn.cpp:119:81: error: expected ')' before 'zend_is_true'
     core::SQLSetConnectAttr(conn, Attr, reinterpret_cast<SQLPOINTER>((zend_long)zend_is_true(value)),
                                                                                 ^
/tmp/sqlsrv/conn.cpp:120:31: error: expected ';' before ')' token
      SQL_IS_UINTEGER TSRMLS_CC);
                               ^
/tmp/sqlsrv/conn.cpp: At global scope:
/tmp/sqlsrv/conn.cpp:136:48: error: 'zend_string' has not been declared
 void add_conn_option_key( sqlsrv_context& ctx, zend_string* key, size_t key_len,
                                                ^
/tmp/sqlsrv/conn.cpp:138:48: error: 'zend_string' has not been declared
 void add_stmt_option_key( sqlsrv_context& ctx, zend_string* key, size_t key_len, HashTable* options_ht, zval* data TSRMLS_DC );
                                                ^
/tmp/sqlsrv/conn.cpp:139:47: error: 'zend_string' has not been declared
 int get_conn_option_key( sqlsrv_context& ctx, zend_string* key, size_t key_len, zval const* value_z TSRMLS_DC );
                                               ^
/tmp/sqlsrv/conn.cpp:140:26: error: 'zend_string' was not declared in this scope
 int get_stmt_option_key( zend_string* key, size_t key_len TSRMLS_DC );
                          ^
/tmp/sqlsrv/conn.cpp:140:39: error: 'key' was not declared in this scope
 int get_stmt_option_key( zend_string* key, size_t key_len TSRMLS_DC );
                                       ^
/tmp/sqlsrv/conn.cpp:140:51: error: expected primary-expression before 'key_len'
 int get_stmt_option_key( zend_string* key, size_t key_len TSRMLS_DC );
                                                   ^
/tmp/sqlsrv/conn.cpp:140:69: error: expression list treated as compound expression in initializer [-fpermissive]
 int get_stmt_option_key( zend_string* key, size_t key_len TSRMLS_DC );
                                                                     ^
/tmp/sqlsrv/conn.cpp:146:75: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
 char* ss_sqlsrv_conn::resource_name = static_cast<char *>("ss_sqlsrv_conn");
                                                                           ^
In file included from /tmp/sqlsrv/conn.cpp:20:0:
/tmp/sqlsrv/conn.cpp: In function 'void zif_sqlsrv_connect(int, zval*, zval**, zval*, int)':
/tmp/sqlsrv/php_sqlsrv.h:285:50: error: 'sqlsrv' was not declared in this scope
 #define SQLSRV_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(sqlsrv, v)
                                                  ^
/tmp/sqlsrv/php_sqlsrv.h:458:4: note: in expansion of macro 'SQLSRV_G'
    SQLSRV_G( current_subsystem ) = current_log_subsystem; \
    ^
/tmp/sqlsrv/conn.cpp:415:5: note: in expansion of macro 'LOG_FUNCTION'
     LOG_FUNCTION( "sqlsrv_connect" );
     ^
/tmp/sqlsrv/php_sqlsrv.h:458:14: error: 'current_subsystem' was not declared in this scope
    SQLSRV_G( current_subsystem ) = current_log_subsystem; \
              ^
/tmp/sqlsrv/php_sqlsrv.h:285:58: note: in definition of macro 'SQLSRV_G'
 #define SQLSRV_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(sqlsrv, v)
                                                          ^
/tmp/sqlsrv/conn.cpp:415:5: note: in expansion of macro 'LOG_FUNCTION'
     LOG_FUNCTION( "sqlsrv_connect" );
     ^
/tmp/sqlsrv/php_sqlsrv.h:285:59: error: 'ZEND_MODULE_GLOBALS_ACCESSOR' was not declared in this scope
 #define SQLSRV_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(sqlsrv, v)
                                                           ^
/tmp/sqlsrv/php_sqlsrv.h:458:4: note: in expansion of macro 'SQLSRV_G'
    SQLSRV_G( current_subsystem ) = current_log_subsystem; \
    ^
/tmp/sqlsrv/conn.cpp:415:5: note: in expansion of macro 'LOG_FUNCTION'
     LOG_FUNCTION( "sqlsrv_connect" );
     ^
/tmp/sqlsrv/conn.cpp:427:23: error: 'ZVAL_UNDEF' was not declared in this scope
     ZVAL_UNDEF(&conn_z);
                       ^
/tmp/sqlsrv/conn.cpp:468:27: error: 'Z_RES' was not declared in this scope
   RETURN_RES( Z_RES(conn_z) );
                           ^
/tmp/sqlsrv/conn.cpp:468:29: error: 'RETURN_RES' was not declared in this scope
   RETURN_RES( Z_RES(conn_z) );
                             ^
In file included from /tmp/sqlsrv/conn.cpp:20:0:
/tmp/sqlsrv/conn.cpp: In function 'void zif_sqlsrv_begin_transaction(int, zval*, zval**, zval*, int)':
/tmp/sqlsrv/php_sqlsrv.h:285:50: error: 'sqlsrv' was not declared in this scope
 #define SQLSRV_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(sqlsrv, v)
                                                  ^
/tmp/sqlsrv/php_sqlsrv.h:458:4: note: in expansion of macro 'SQLSRV_G'
    SQLSRV_G( current_subsystem ) = current_log_subsystem; \
    ^
/tmp/sqlsrv/conn.cpp:512:5: note: in expansion of macro 'LOG_FUNCTION'
     LOG_FUNCTION( "sqlsrv_begin_transaction" );
     ^
/tmp/sqlsrv/php_sqlsrv.h:458:14: error: 'current_subsystem' was not declared in this scope
    SQLSRV_G( current_subsystem ) = current_log_subsystem; \
              ^
/tmp/sqlsrv/php_sqlsrv.h:285:58: note: in definition of macro 'SQLSRV_G'
 #define SQLSRV_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(sqlsrv, v)
                                                          ^
/tmp/sqlsrv/conn.cpp:512:5: note: in expansion of macro 'LOG_FUNCTION'
     LOG_FUNCTION( "sqlsrv_begin_transaction" );
     ^
/tmp/sqlsrv/php_sqlsrv.h:285:59: error: 'ZEND_MODULE_GLOBALS_ACCESSOR' was not declared in this scope
 #define SQLSRV_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(sqlsrv, v)
                                                           ^
/tmp/sqlsrv/php_sqlsrv.h:458:4: note: in expansion of macro 'SQLSRV_G'
    SQLSRV_G( current_subsystem ) = current_log_subsystem; \
    ^
/tmp/sqlsrv/conn.cpp:512:5: note: in expansion of macro 'LOG_FUNCTION'
     LOG_FUNCTION( "sqlsrv_begin_transaction" );
     ^
/tmp/sqlsrv/conn.cpp: In function 'void zif_sqlsrv_close(int, zval*, zval**, zval*, int)':
/tmp/sqlsrv/php_sqlsrv.h:285:50: error: 'sqlsrv' was not declared in this scope
 #define SQLSRV_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(sqlsrv, v)
                                                  ^
/tmp/sqlsrv/php_sqlsrv.h:458:4: note: in expansion of macro 'SQLSRV_G'
    SQLSRV_G( current_subsystem ) = current_log_subsystem; \
    ^
/tmp/sqlsrv/conn.cpp:558:5: note: in expansion of macro 'LOG_FUNCTION'
     LOG_FUNCTION( "sqlsrv_close" );
     ^
/tmp/sqlsrv/php_sqlsrv.h:458:14: error: 'current_subsystem' was not declared in this scope
    SQLSRV_G( current_subsystem ) = current_log_subsystem; \
              ^
/tmp/sqlsrv/php_sqlsrv.h:285:58: note: in definition of macro 'SQLSRV_G'
 #define SQLSRV_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(sqlsrv, v)
                                                          ^
/tmp/sqlsrv/conn.cpp:558:5: note: in expansion of macro 'LOG_FUNCTION'
     LOG_FUNCTION( "sqlsrv_close" );
     ^
/tmp/sqlsrv/php_sqlsrv.h:285:59: error: 'ZEND_MODULE_GLOBALS_ACCESSOR' was not declared in this scope
 #define SQLSRV_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(sqlsrv, v)
                                                           ^
/tmp/sqlsrv/php_sqlsrv.h:458:4: note: in expansion of macro 'SQLSRV_G'
    SQLSRV_G( current_subsystem ) = current_log_subsystem; \
    ^
/tmp/sqlsrv/conn.cpp:558:5: note: in expansion of macro 'LOG_FUNCTION'
     LOG_FUNCTION( "sqlsrv_close" );
     ^
/tmp/sqlsrv/conn.cpp:589:83: error: 'Z_RES_P' was not declared in this scope
         conn = static_cast<ss_sqlsrv_conn*>( zend_fetch_resource( Z_RES_P( conn_r ) TSRMLS_CC, ss_sqlsrv_conn::resource_name, ss_sqlsrv_conn::descriptor ));
                                                                                   ^
/tmp/sqlsrv/conn.cpp:592:29: error: 'Z_RES_TYPE_P' was not declared in this scope
   if ( Z_RES_TYPE_P( conn_r ) == RSRC_INVALID_TYPE) {
                             ^
/tmp/sqlsrv/conn.cpp:606:48: error: 'zend_list_close' was not declared in this scope
         if( zend_list_close( Z_RES_P( conn_r ) ) == FAILURE ) {
                                                ^
In file included from /tmp/sqlsrv/php_sqlsrv.h:25:0,
                 from /tmp/sqlsrv/conn.cpp:20:
/tmp/sqlsrv/conn.cpp:607:98: error: 'Z_RES_HANDLE_P' was not declared in this scope
             LOG( SEV_ERROR, "Failed to remove connection resource %1!d!", Z_RES_HANDLE_P( conn_r ));
                                                                                                  ^
/tmp/sqlsrv/shared/core_sqlsrv.h:274:79: note: in definition of macro 'LOG'
 #define LOG( severity, msg, ...)    write_to_log( severity TSRMLS_CC, msg, ## __VA_ARGS__ )
                                                                               ^
/tmp/sqlsrv/conn.cpp: At global scope:
/tmp/sqlsrv/conn.cpp:624:32: error: variable or field 'sqlsrv_conn_dtor' declared void
 void __cdecl sqlsrv_conn_dtor( zend_resource *rsrc TSRMLS_DC )
                                ^
/tmp/sqlsrv/conn.cpp:624:32: error: 'zend_resource' was not declared in this scope
/tmp/sqlsrv/conn.cpp:624:47: error: 'rsrc' was not declared in this scope
 void __cdecl sqlsrv_conn_dtor( zend_resource *rsrc TSRMLS_DC )
                                               ^
In file included from /tmp/sqlsrv/conn.cpp:20:0:
/tmp/sqlsrv/php_sqlsrv.h: In instantiation of 'H* process_params(int, zval*, zval**, zval*, int, const char*, const char*, size_t, ...) [with H = ss_sqlsrv_conn; zval = _zval_struct; size_t = long unsigned int]':
/tmp/sqlsrv/conn.cpp:516:5:   required from here
/tmp/sqlsrv/php_sqlsrv.h:598:62: error: 'Z_RES_P' was not declared in this scope
         h = static_cast<H*>( zend_fetch_resource(Z_RES_P(rsrc) TSRMLS_CC, H::resource_name, H::descriptor ));
                                                              ^
make: *** [conn.lo] Error 1
ERROR: `make' failed
`

**Comment by Tklaversma** [comment]
@davidlapham  I updated my script. You have to run `yum groupinstall 'Development Tools'` before installing MSPHPSQL. This will install all the necessary tools needed.

Furthermore, I see you are trying to install the development version (4.1.6.1). Use the latest production version > 4.0.8.

**Comment by davidlapham** [comment]
@Tklaversma ran the install and still no luck.  Any other thoughts?  On day 4 of trying to get this to work 👎

**Comment by Tklaversma** [comment]
@davidlapham whats the error output after u installed the Development Tools?

**Comment by davidlapham** [comment]
Same thing.  Tried restarting apache

**Comment by Tklaversma** [comment]
@davidlapham you can email me, so we can skype/teamviewer. I'll help you out.
tklaversma@gmail..

**Comment by davidlapham** [comment]
![screen shot 2017-02-13 at 1 56 47 pm](https://cloud.githubusercontent.com/assets/6608283/22898174/52a3584c-f1f4-11e6-9c17-5ab725e03140.png)

**Comment by meet-bhagdev** [comment]
@Tklaversma Thanks for the help :) 
I am happy to help as well: meetb@microsoft.com

Just to clarify, did you install the ODBC Driver? If so what are the steps you followed?

**Comment by donaldallen** [comment]
@davidlapham I'm having the same error. Did you ever solve this?

**Comment by donaldallen** [comment]
Okay, I was able to get this working without having to update Cent OS's PHP, as Media Temple claims it will [break your server](https://mediatemple.net/community/products/dv/207889153/what's-new-in-php-7#5). I mostly followed the steps @Tklaversma mentions, but I had to also install ```plesk-php70-devel``` in order to successfully install the pecl modules ([as per this Plesk post](https://www.plesk.com/product-technology/adding-custom-php-modules-in-plesk)).

**Comment by Tklaversma** [comment]
So... I've been having some problems with the latest Plesk 17.5.3 in combination with Php 7.1.
I've got it fully working now and thought it would be nice to share my "script" (more a list of commands).

**Pre-requisites:**
1. Linux server CentOS 7.*
2. Plesk 17.*
3. Php 7.1.*

**What does this script do?**
1. Update Plesk with the latest minor updates
2. Turns off SELinux
3. Install all necessary libraries
4. Replaces the current ODBC Driver with the latest one
5. Installs the unixODBC 2.3.1 (PDO is only supported with unixODBC 2.3.1)
6. Installs `sqlsrv-4.1.9preview` and `pdo_sqlsrv-4.1.9preview` (of course you can replace this with any 4.1.7+ version you'd like)
7. Enables `sqlsrv` and `pdo_sqlsrv` for Php 7.1 in Plesk

**The script**
```
# Update Plesk and install pre-requisites
/usr/local/psa/admin/sbin/autoinstaller --select-product-id plesk --select-release-current --reinstall-patch --install-component base
yum clean all
yum -y update && yum -y upgrade
yum -y install yum-utils gcc
yum -y install libmpc-devel mpfr-devel gmp-devel php-devel
yum -y group install "Development Tools"
setsebool -P httpd_can_network_connect_db 1


# Remove old ODBC Driver
rm -rf /usr/bin/sqlcmd
rm -rf /usr/bin/bcp
rm -rf /opt/microsoft/msodbcsql
rm -rf /tmp/msodbcrhel
rm -rf /usr/lib64/msodbcsql-13.*
rm -rf /usr/lib64/libodbc*
odbcinst -u -d -n "ODBC Driver 11 for SQL Server"


# Install unixODBC 2.3.1
mkdir /tmp/msodbcrhel
wget ftp://ftp.unixodbc.org/pub/unixODBC/unixODBC-2.3.1.tar.gz -P /tmp/msodbcrhel/
tar -xzf /tmp/msodbcrhel/unixODBC-2.3.1.tar.gz
cd /tmp/msodbcrhel/
tar -xzf unixODBC-2.3.1.tar.gz
cd /tmp/msodbcrhel/unixODBC-2.3.1
sudo -i export CPPFLAGS="-DSIZEOF_LONG_INT=8"
./configure --prefix=/usr --libdir=/usr/lib64 --sysconfdir=/etc --enable-gui=no --enable-drivers=no --enable-iconv --with-iconv-char-enc=UTF8 --with-iconv-ucode-enc=UTF16LE --enable-stats=no 1> configure_std.log 2> configure_err.log
make 1> make_std.log 2> make_err.log
make install 1> makeinstall_std.log 2> makeinstall_err.log
cd /usr/lib64
sudo ln -s libodbccr.so.2   libodbccr.so.1
sudo ln -s libodbcinst.so.2 libodbcinst.so.1
sudo ln -s libodbc.so.2     libodbc.so.1


# Install latest ODBC driver with yum (this way, we can keep updating it with `yum -y update`)
cd /tmp/
yum-config-manager --add-repo https://apt-mo.trafficmanager.net/yumrepos/mssql-rhel7-release/
yum-config-manager --enable mssql-rhel7-release
wget "http://aka.ms/msodbcrhelpublickey/dpgswdist.v1.asc"
rpm --import dpgswdist.v1.asc
yum clean all
yum -y update && yum -y upgrade
ACCEPT_EULA=Y yum -y install msodbcsql mssql-tools unixODBC-devel unixODBC-utf16-devel
echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
source ~/.bashrc


# Install sqlsrv 4.1.9preview
pecl install sqlsrv-4.1.9preview
pecl install pdo_sqlsrv-4.1.9preview
sed -i 1,2d /etc/php.ini


# Make sure sqlsrv is loaded for php 7.1
rm -rf /opt/plesk/php/7.*/etc/php.d/sqlsrv.ini
echo -e "/usr/lib64/php/modules/sqlsrv.so\n/usr/lib64/php/modules/pdo_sqlsrv.so" >> /opt/plesk/php/7.1/etc/php.d/sqlsrv.ini


# Restart Apache
plesk bin php_handler --reread
service httpd restart
```
