### ISSUE TITLE
Error information: SQLSTATE[HYT00]: [unixODBC][Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired

### ISSUE THREAD

**Issue by namsudtho** [Microsoft/msphpsql#679]
+## Driver version or file name
 +php72-php-sqlsrv-x86_64-5.2.0~RC1-1.el7.remi
 +
 +## SQL Server version
 +Please tell us what the SQL Server version is.
 +
 +## Client operating system
 +CentOS 7.4
 +
 +## PHP version
 +PHP 7.2
 +
 +## Microsoft ODBC Driver version
 +ODBC Driver 17 for SQL Server
 +
 +## Table schema
 +Please tell us the table schema
 +
 +## Problem description
 +SQLSTATE[HYT00]: [unixODBC][Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired
 +
 +## Expected behavior and actual behavior
 +Please tell us what should happen and what happened instead
 +
 +## Repro code
This is the page I test to connect using the sqlcmd command.
![image](https://user-images.githubusercontent.com/15089720/35669074-7ea966d8-0766-11e8-9ddf-6f672bb2d155.png)

This is the page I test to connect with the php language.
![image](https://user-images.githubusercontent.com/15089720/35669351-6270320c-0767-11e8-9403-56b3359299b4.png)

This is the page that outputs the code above.
![image](https://user-images.githubusercontent.com/15089720/35669473-c493b508-0767-11e8-8219-a3e347b6172a.png)

**Comment by david-puglielli** [comment]
Hi @namsudtho, it looks like you are trying to connect to a named instance. To connect to a named instance, you need to specify the port in the connection string. For example, if you are using the standard SQL Server port (1433), try

```
$dbh = new PDO("sqlsrv:Server=$host,1433;Database=$dbname", $user, $pass);
```
Issue  #190 and this [link](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/connection-string-keywords-and-data-source-names-dsns) may help.

**Comment by namsudtho** [comment]
Thank you for your help.
But I found another problem. Error message displayed by image.
I am sure my "username" and "password" are correct.
![image](https://user-images.githubusercontent.com/15089720/35798280-e407a6a8-0a94-11e8-81b3-5465d2b62bb6.png)

**Comment by david-puglielli** [comment]
That error message can pop up if the name of the database is wrong as well, so you should double check that. Also, why does it say `ODBC Driver 13` when you were using 17? If you are running multiple instance of the ODBC driver you can use the Driver keyword to pick one; for example, add the following to the connection string:
```
Driver={ODBC Driver 17 for SQL Server};
```

**Comment by namsudtho** [comment]
Hi @david-puglielli, I try to follow the way you tell everything. But it still does not connect. Please remote to help?

**Comment by benyanke** [comment]
I'm getting this happening randomly as well. I know(?) it's not a config issue, as it only happens intermittently. Any ideas as to why this may happen intermittently?

```
Next Illuminate\Database\QueryException: SQLSTATE[HYT00]: [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]Login timeout expired (SQL: Select [...] from [...])
```

**Comment by david-puglielli** [comment]
@benyanke @namsudtho If the error message is intermittent, it may be caused by an issue in version 13 of the ODBC driver affecting time stamps. This has been fixed in the latest release of the ODBC driver, available [here](https://www.microsoft.com/en-us/download/details.aspx?id=56567) or through your [package manager](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server). 

Even if the error message is not intermittent, I would advise trying the latest ODBC driver as well from the links above, as it has just gone RTW. Please let us know if this fixes the issue.

**Comment by namsudtho** [comment]
@benyanke I have installed the latest package that you recommended. But it still does not work. 
error message
`SQLSTATE[28000]: [unixODBC][Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user '...'.`

**Comment by benyanke** [comment]
@david-puglielli is there a way to use the latest version with pdo_sqlsrv from pecl? Having the latest ODBC driver is all well and good, but if the rest of the stack doesn't support it, we're still out of luck.

![image](https://user-images.githubusercontent.com/4274911/36117861-c800ed90-1000-11e8-845d-9474b242e7bf.png)

**Comment by david-puglielli** [comment]
@benyanke you can download using `pecl install pdo_sqlsrv-5.2.0RC1` to get the latest preview. (`pecl install pdo_sqlsrv` only installs the latest stable release, which is version 4.3 and does not support the Driver keyword.)

**Comment by yitam** [comment]
@benyanke @namsudtho we are closing this issue due to inactivity. Please feel free to reopen if you still have any question.

**Comment by gbili** [comment]
I have tried all possible ways to connect to SQLEXPRESS from macOS High Sierra using ODBC, sqlsrv, mssql, FreeTDS, unixodbc and it is just impossible. Following every step in:
[Microsoft1](https://docs.microsoft.com/en-gb/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017)
[Microsoft2](https://docs.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-2017)
It just won't work. I've gotten all sorts of errors, searched for the solutions in each one, and there is no way, just no way to solve it. Always clueless errors.

`Fatal error: Uncaught PDOException: SQLSTATE[08001]: [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x2746 in`

`Fatal error: Uncaught PDOException: SQLSTATE[IMSSP]: An invalid keyword '"Driver' was specified in the DSN string. in`

`Warning: odbc_connect(): SQL error: [unixODBC][Driver Manager]Invalid string or buffer length, SQL state S1090 in SQLConnect in`

`Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : TCP Provider: Error code 0x2AF9.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..`

`locale is "en_US.UTF-8"
locale charset is "UTF-8"
using default charset "UTF-8"
Error 20017 (severity 9):
	Unexpected EOF from the server
Error 20002 (severity 9):
	Adaptive Server connection failed
There was a problem connecting to the server`

`Error 20012 (severity 2):
	Server name not found in configuration files.
locale is "en_US.UTF-8"
locale charset is "UTF-8"
using default charset "UTF-8"
Error 20013 (severity 2):
	Unknown host machine name.
Error 20009 (severity 9):
	Unable to connect: Adaptive Server is unavailable or does not exist
There was a problem connecting to the server`

I've already wasted 2 days of my life trying to figure this out, but the documentation is so bad (useless). It will be faster to just export the database and use some other vendor.

**Comment by raylucker** [comment]
> @benyanke @namsudtho If the error message is intermittent, it may be caused by an issue in version 13 of the ODBC driver affecting time stamps. This has been fixed in the latest release of the ODBC driver, available [here](https://www.microsoft.com/en-us/download/details.aspx?id=56567) or through your [package manager](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server).
> 
> Even if the error message is not intermittent, I would advise trying the latest ODBC driver as well from the links above, as it has just gone RTW. Please let us know if this fixes the issue.

Tried to use this suggestion to my problem. But it ends up on this error "SQLSTATE[IM004]: [Microsoft][ODBC Driver Manager] Driver's SQLAllocHandle on SQL_HANDLE_ENV failed"

**Comment by williammoreschi** [comment]
I am having trouble connecting the database. I created a new VM using Ubuntu 18.4 LTS.
I followed the steps given on the Microsoft website (https://bit.ly/2Mfz7YZ).

sudo su
add-apt-repository ppa:ondrej/php -y
apt-get update
apt-get install php7.3 php7.3-dev php7.3-xml -y --allow-unauthenticated
curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
exit
sudo apt-get update
sudo ACCEPT_EULA=Y apt-get install msodbcsql17
sudo ACCEPT_EULA=Y apt-get install mssql-tools
echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
source ~/.bashrc
sudo apt-get install unixodbc-dev
sudo pecl install sqlsrv
sudo pecl install pdo_sqlsrv
sudo su
echo extension=pdo_sqlsrv.so >> `php --ini | grep "Scan for additional .ini files" | sed -e "s|.*:\s*||"`/30-pdo_sqlsrv.ini
echo extension=sqlsrv.so >> `php --ini | grep "Scan for additional .ini files" | sed -e "s|.*:\s*||"`/20-sqlsrv.ini
exit
sudo su
apt-get install libapache2-mod-php7.2 apache2
a2dismod mpm_event
a2enmod mpm_prefork
a2enmod php7.3
echo "extension=pdo_sqlsrv.so" >> /etc/php/7.3/apache2/conf.d/30-pdo_sqlsrv.ini
echo "extension=sqlsrv.so" >> /etc/php/7.3/apache2/conf.d/20-sqlsrv.ini
exit
sudo service apache2 restart

Using the code below is turning on the error **(SQLSTATE[HYT00]: [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired)**
```
<?
$server = "111.111.111.111\instance";
$db = "DB";
$pass = "xxx";
$user = "yyy";

try {
    $dbh = new PDO('sqlsrv:Server=$server;Database=$db',$user,$pass);
    foreach($dbh->query('SELECT * from users') as $row) {
        print_r($row);
    }
    $dbh = null;
} catch (PDOException $e) {
    print "Error!: " . $e->getMessage() . "<br/>";
}

$server = "111.111.111.111\instance,1433";
$db = "DB";
$pass = "xxx";
$user = "yyy";

try {
    $dbh = new PDO('sqlsrv:Server=$server;Database=$db',$user,$pass);
    foreach($dbh->query('SELECT * from users') as $row) {
        print_r($row);
    }
    $dbh = null;
} catch (PDOException $e) {
    print "Error!: " . $e->getMessage() . "<br/>";
}

?>
```

I also tried using an example from microsoft (https://bit.ly/2H4h0mT)

Error information: 
SQLSTATE: HYT00
Code: 0
Message: [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired
SQLSTATE: 08001
Code: -1
Message: [Microsoft][ODBC Driver 17 for SQL Server]MAX_PROVS: Error Locating Server/Instance Specified [xFFFFFFFF]. 
SQLSTATE: 08001
Code: -1
Message: [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online.

Could someone help me understand the error.
In IIS and XAMPP I made it work.
In ubuntu it does not work.

**Comment by yitam** [comment]
@williammoreschi looks like you're using a named instance, and please check our [FAQ](https://github.com/Microsoft/msphpsql/wiki/FAQ#connect-to-named-instances)

It's high priority for ODBC driver to support named instances. Please stay tuned.

**Comment by williammoreschi** [comment]
HI @yitam 
MY problem was port  by default (1433),  putting or not the error was persistent. I solved the problem using the code ( Sarke - https://bit.ly/2EVY5rZ )

**Comment by yitam** [comment]
Good to know you got it working @williammoreschi 
As mentioned in #927 , this will be fixed in the future releases.
FYI, this is [another reference about setting up DSNs](https://docs.microsoft.com/sql/connect/odbc/linux-mac/connection-string-keywords-and-data-source-names-dsns?view=sql-server-2017)

**Comment by bsakizli** [comment]
Hi,

SSH Command -> **sudo setsebool -P httpd_can_network_connect_db 1**   

:)

**Comment by ShayanGit** [comment]
> Hi @david-puglielli, I'm can connected. Thank you for your help.
Hi @namsudtho, I have the same problem as you. Can you tell me what your problem was?
