### ISSUE TITLE
Using emulate prepares breaks string parameters that contain unicode characters

### ISSUE THREAD

**Issue by david-garcia-garcia** [Microsoft/msphpsql#92]
Someone reported this bug here:

https://www.drupal.org/node/2693763

The issue is that a statement without EMULATE_PREPARES generates the following SQL:

`SELECT * FROM users WHERE name = @P1 AND status = 1',N'@P1 nvarchar(6)',N'가각'`

But when using EMULATE_PREPARES it turns it into:

`SELECT * FROM users WHERE name = '가각' AND status = 1`

When it should be (notice the additional N):

`SELECT * FROM users WHERE name = N'가각' AND status = 1`

There is another issue related to EMULATE_PREPARES not working as expected:

https://github.com/Azure/msphpsql/issues/63

**Comment by meet-bhagdev** [comment]
@david-garcia-garcia we believe this particular issue with the SQL queries listed above is fixed in our latest release - https://github.com/Azure/msphpsql/releases/tag/4.1.0. We are reviewing the other issues you have opened. In the meanwhile can you help us validate this?

**Comment by david-garcia-garcia** [comment]
I can confirm this is not solved :(

I've built a complete test script:

http://pastebin.com/TsLt8Za3

Current Output:

> FOUND: ??sample2
> FOUND: 가각ácasa

Expected Output:

> FOUND: 가각ácasa
> FOUND: 가각ácasa
> FOUND: 가각ácasa
> FOUND: 가각ácasa

**Comment by david-garcia-garcia** [comment]
Repasted the demo script, so that it won't expire as it has happened in other issues:

https://pastebin.com/P8emQQj4

**Comment by david-garcia-garcia** [comment]
I can confirm that latest release fixes this issue. Thanks!!!!!
